#!/usr/bin/env python3
"""Build the self-contained track data bundle for trackfans."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT.parents[0] / "data"
OUTLINE_DIR = ROOT.parents[0] / "site" / "outlines"
OUT = ROOT / "tracks.js"
SEASONS_JSON = ROOT / "seasons.json"
SEASONS_OUT = ROOT / "seasons.js"

FLAGS = {
    "Argentina": "🇦🇷",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Azerbaijan": "🇦🇿",
    "Bahrain": "🇧🇭",
    "Belgium": "🇧🇪",
    "Brazil": "🇧🇷",
    "Canada": "🇨🇦",
    "China": "🇨🇳",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Hungary": "🇭🇺",
    "India": "🇮🇳",
    "Italy": "🇮🇹",
    "Japan": "🇯🇵",
    "Malaysia": "🇲🇾",
    "Mexico": "🇲🇽",
    "Monaco": "🇲🇨",
    "Morocco": "🇲🇦",
    "Netherlands": "🇳🇱",
    "Portugal": "🇵🇹",
    "Qatar": "🇶🇦",
    "Russia": "🇷🇺",
    "Saudi Arabia": "🇸🇦",
    "Singapore": "🇸🇬",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "Spain": "🇪🇸",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Turkey": "🇹🇷",
    "United Arab Emirates": "🇦🇪",
    "United Kingdom": "🇬🇧",
    "United States": "🇺🇸",
}


def read_outline_path(track_id: str) -> str | None:
    svg_path = OUTLINE_DIR / f"{track_id}.svg"
    if not svg_path.exists():
        return None
    text = svg_path.read_text(encoding="utf-8")
    match = re.search(r"<path\b[^>]*\bd=[\"']([^\"']+)[\"']", text)
    if not match:
        raise ValueError(f"Outline has no path d attribute: {svg_path}")
    return match.group(1)


def write_seasons() -> int:
    """Regenerate seasons.js from seasons.json on every build."""
    if SEASONS_JSON.exists():
        seasons_obj = json.loads(SEASONS_JSON.read_text(encoding="utf-8"))
    else:
        seasons_obj = {}
    payload = json.dumps(seasons_obj, ensure_ascii=False, separators=(",", ":"))
    SEASONS_OUT.write_text(
        "// Generated by build.py. Do not edit by hand.\n"
        f"const SEASONS = {payload};\n",
        encoding="utf-8",
    )
    return len(seasons_obj)


def main() -> None:
    records = []
    outline_files = []
    for path in sorted(DATA_DIR.glob("*.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        if record["id"] != path.stem:
            raise ValueError(f"id/filename mismatch: {path}")
        outline_d = read_outline_path(record["id"])
        record["outline_d"] = outline_d
        record["outline_id"] = record["id"] if outline_d else None
        if outline_d:
            outline_files.append(f"{record['id']}.svg")
        record["flag"] = FLAGS.get(record["country"], "")
        records.append(record)

    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    outline_payload = json.dumps(outline_files, separators=(",", ":"))
    OUT.write_text(
        "// Generated by build.py. Do not edit by hand.\n"
        f"window.TRACKFANS_OUTLINE_FILES = {outline_payload};\n"
        f"window.TRACKFANS_TRACKS = {payload};\n",
        encoding="utf-8",
    )
    outlines = sum(1 for record in records if record["outline_d"])
    print(f"Wrote {OUT.name}: {len(records)} circuits, {outlines} outlines")

    season_count = write_seasons()
    print(f"Wrote {SEASONS_OUT.name}: {season_count} seasons")


if __name__ == "__main__":
    main()
